---
- hosts: localhost
  gather_facts: no
  vars_files:
    - "{{demo}}/setup.yml"
  vars:
    controller_validate_certs: false

  tasks:
    - name: Setup Components
      include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      when:
        - controller_components | d("") | length > 0

    - name: Create ServiceNow Application
      ansible.builtin.uri:
        url: https://aap-controller.4rr4p.internal/api/v2/applications/
        user: "{{ uri_user }}"
        password: "{{ uri_password }}"
        method: POST
        force_basic_auth: true
        body_format: json
        body:
          name: Brian ServiceNow Dev
          description: "{{ instance }}"
          organization: "1"
          authorization_grant_type: "authorization-code"
          redirect_uris: "https://{{ instance }}.service-now.com/oauth_redirect.do"
          client_type: "confidential"
      register: snow_result

    
    # - name: Create ServiceNow Application
    #   ansible.controller.application:
    #     name: Brian ServiceNow Dev
    #     description: "{{ instance }}"
    #     organization: "Default"
    #     authorization_grant_type: "authorization-code"
    #     redirect_uris: "https://{{ instance }}.service-now.com/oauth_redirect.do"
    #     client_type: "confidential"
    #   register: snow_result

    - name: Print Message
      debug:
        msg: "{{ snow_result }}"