---
- name: Demo Setup
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{demo}}/setup.yml"

  tasks:
    - name: Setup Components
      ansible.builtin.include_role:
        name: "infra.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      when:
        - controller_components | d("") | length > 0
