---
- hosts: localhost
  gather_facts: no
  vars_files:
    - "{{demo}}/setup.yml"
  vars:
    controller_validate_certs: false
    # Controller user for URI module call
    uri_user: admin
    # Controller user password for URI module call
    uri_password: MzMzODc2
    # Controller base URL prefix (e.g. aap-controller.4rr4p)
    controller_url_prefix: aap-controller.4rr4p
    # Controller base URL suffix (e.g. sandbox2307.opentlc.com)
    controller_url_suffix: sandbox1234.opentlc.com


  tasks:
    - name: Setup Components
      include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      when:
        - controller_components | d("") | length > 0

    - name: Create ServiceNow Application
      ansible.builtin.uri:
        url: "https://{{ controller_url_prefix }}.internal/api/v2/applications/"
        user: "{{ uri_user }}"
        password: "{{ uri_password }}"
        method: POST
        force_basic_auth: true
        body_format: json
        body:
          name: Brian ServiceNow Dev
          description: "{{ instance }}"
          organization: "1"
          authorization_grant_type: "authorization-code"
          redirect_uris: "https://{{ instance }}.service-now.com/oauth_redirect.do"
          client_type: "confidential"
        status_code: 201
      register: snow_app_result

    - name: Print Message
      debug:
        msg: "{{ snow_app_result }}"

    - name: Print Message
      debug:
        var: snow_app_result.json.client_secret
      # register: client_secret

    - name: Set client secret and ID variables
      set_fact:
        client_secret: "{{ snow_app_result.json.client_secret }}"
        client_id: "{{ snow_app_result.json.client_id }}"

    - name: Print Message
      debug:
        var: client_secret

    - name: Print Message
      debug:
        msg: 
        - "This is your client secret: {{ client_secret }}"
        - "This is your client ID: {{ client_id }}"

    - name: Update Application Registries for AAP OAuth Provider
      snow_record:
        username: "{{ username }}"
        password: "{{ password }}"
        instance: "{{ instance }}"
        state: present
        table: oauth_entity
        lookup_field: sys_id
        number: 3f4733652fd121108779d6c6f699b65a
        data: 
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          auth_url: "https://{{ controller_url_prefix }}.{{ controller_url_suffix }}/api/o/authorize/"
          token_url: "https://{{ controller_url_prefix }}.{{ controller_url_suffix }}/api/o/token/"

    - name: Update REST Message for Deploy App on Pre-Prod
      snow_record:
        username: "{{ username }}"
        password: "{{ password }}"
        instance: "{{ instance }}"
        state: present
        table: sys_rest_message
        lookup_field: sys_id
        number: 9b2afbe52fd121108779d6c6f699b6f6
        data: 
          rest_endpoint: "https://{{ controller_url_prefix }}.{{ controller_url_suffix }}/api/v2/workflow_job_templates/45/launch/"

    - name: Update HTTP Method for REST Message for Deploy App on Pre-Prod
      snow_record:
        username: "{{ username }}"
        password: "{{ password }}"
        instance: "{{ instance }}"
        state: present
        table: sys_rest_message_fn
        lookup_field: sys_id
        number: 097bbf292fd121108779d6c6f699b6fb
        data: 
          rest_endpoint: "https://{{ controller_url_prefix }}.{{ controller_url_suffix }}/api/v2/workflow_job_templates/45/launch/"
